# Single-node Elasticsearch cluster with Kibana, Logstash, and Beats
# Resources:
# - https://www.elastic.co/blog/getting-started-with-the-elastic-stack-and-docker-compose
# - https://www.elastic.co/docs/deploy-manage/deploy/self-managed/install-elasticsearch-docker-basic
# - https://www.elastic.co/docs/deploy-manage/deploy/self-managed/install-elasticsearch-docker-compose
# - https://www.elastic.co/docs/deploy-manage/deploy/self-managed/install-kibana-with-docker
# - https://github.com/elastic/elasticsearch/tree/main/docs/reference/setup/install/docker

services:
  setup-certs:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    restart: "no"
    user: "0"
    command: /usr/share/elasticsearch/setup_certs.sh
    volumes:
      - ./certs/setup_certs.sh:/usr/share/elasticsearch/setup_certs.sh:ro
      - ./certs/instances.yml:/usr/share/elasticsearch/config/instances.yml:ro
      - ./certs/entities/:/usr/share/elasticsearch/config/certs
    network_mode: none
    profiles:
      - certs

  setup-users:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    restart: "no"
    user: "0"
    command: /usr/share/elasticsearch/setup_users.sh
    volumes:
      - ./setup/setup_users.sh:/usr/share/elasticsearch/setup_users.sh:ro
      - ./certs/entities/ca_pub/:/usr/share/elasticsearch/config/certs/ca:ro
      # Needed to set the correct permissions for the snapshots directory for elasticsearch services
      - ./snapshots/:/usr/share/elasticsearch/snapshots
    environment:
      ES_HOST: "https://es01:9200"
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      KIBANA_PASSWORD: ${KIBANA_PASSWORD}
      LOGSTASH_PASSWORD: ${LOGSTASH_PASSWORD}
      BEATS_PASSWORD: ${BEATS_PASSWORD}
    networks:
      - internal
    depends_on:
      es01:
        condition: service_healthy

  # NOTE: This is a simple service that is used to generate Kibana encryption keys
  # It is intended to be a one-shot container and run independently of the main stack
  generate-kibana-keys:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    command: /usr/share/kibana/bin/kibana-encryption-keys generate
    network_mode: none
    profiles:
      - kibana-keys

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    restart: unless-stopped
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./certs/entities/ca_pub/:/usr/share/elasticsearch/config/certs/ca:ro
      - ./certs/entities/es01/:/usr/share/elasticsearch/config/certs/es01:ro
      - ./snapshots/:/usr/share/elasticsearch/snapshots
      - es01_data:/usr/share/elasticsearch/data
    environment:
      NODE_NAME: es01
      CLUSTER_NAME: ${ES_CLUSTER_NAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      LICENSE: ${LICENSE}
      # NOTE: Set to false if using Docker in rootless mode
      MEMORY_LOCK: true
      discovery.type: single-node
    ports:
      # By default binds to localhost only (see env file)
      - ${ES_PORT}:9200
    networks:
      - internal
    mem_limit: ${ES_MEM_LIMIT}
    # NOTE: Comment out if using Docker in rootless mode (container cannot have unlimited locked-in-memory address space)
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'"]
      interval: 10s
      timeout: 30s
      retries: 120
    # NOTE: Not needed if setup-certs service runs separately to generate certificates or if external certificates are used
    #depends_on:
    #  setup-certs:
    #    condition: service_completed_successfully
    labels:
      co.elastic.logs/module: elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    restart: unless-stopped
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - ./certs/entities/ca_pub/:/usr/share/kibana/config/certs/ca:ro
      - ./certs/entities/kibana/:/usr/share/kibana/config/certs/kibana:ro
      - kibana_data:/usr/share/kibana/data
    environment:
      ES_HOSTS: '["https://es01:9200"]'
      SERVER_NAME: kibana
      KIBANA_USER: kibana_system
      KIBANA_PASSWORD: ${KIBANA_PASSWORD}
      ENCRYPTED_SAVED_OBJECTS_ENCRYPTION_KEY: ${KIBANA_ENCRYPTED_SAVED_OBJECTS_ENCRYPTION_KEY:?set encryption key}
      REPORTING_ENCRYPTION_KEY: ${KIBANA_REPORTING_ENCRYPTION_KEY:?set encryption key}
      SECURITY_ENCRYPTION_KEY: ${KIBANA_SECURITY_ENCRYPTION_KEY:?set encryption key}
    ports:
      # By default binds to localhost only (see env file)
      - ${KIBANA_PORT}:5601
    networks:
      - internal
    mem_limit: ${KB_MEM_LIMIT}
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS --cacert config/certs/ca/ca.crt https://localhost:5601/"]
      interval: 10s
      timeout: 10s
      retries: 120
    depends_on:
      es01:
        condition: service_healthy
      setup-users:
        condition: service_completed_successfully
    labels:
      co.elastic.logs/module: kibana

  logstash:
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
    # INFO: You can specify which pipeline to run with a -f option
    # In that case, Logstash will ignore the pipelines.yml file
    # When you start Logstash without arguments, it will read the pipelines.yml file and instantiate all pipelines specified in the file
    # command: /usr/share/logstash/bin/logstash -f /usr/share/logstash/pipeline/logstash-apache.conf
    # INFO: Test logstash pipeline configuration
    # command: /usr/share/logstash/bin/logstash -f /usr/share/logstash/pipeline/logstash-json.conf --config.test_and_exit
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/:ro
      - ./logstash/ingest-data/:/usr/share/logstash/ingest-data/:ro
      - ./certs/entities/ca_pub/:/usr/share/logstash/config/certs/ca:ro
      - logstash_data:/usr/share/logstash/data
    environment:
      ES_HOSTS: "https://es01:9200"
      LOGSTASH_USER: logstash_internal
      LOGSTASH_PASSWORD: ${LOGSTASH_PASSWORD}
      SSL_CERTIFICATE_AUTHORITIES: /usr/share/logstash/config/certs/ca/ca.crt
    networks:
      - internal
    mem_limit: ${LS_MEM_LIMIT}
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9600/ > /dev/null"]
      interval: 10s
      timeout: 10s
      retries: 120
    profiles:
      - logstash
      - ingest
    depends_on:
      es01:
        condition: service_healthy
      setup-users:
        condition: service_completed_successfully
    labels:
      co.elastic.logs/module: logstash

  filebeat:
    image: docker.elastic.co/beats/filebeat:${STACK_VERSION}
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./filebeat/ingest-data/:/usr/share/filebeat/ingest-data:ro
      - ./certs/entities/ca_pub/:/usr/share/filebeat/certs/ca:ro
      - filebeat_data:/usr/share/filebeat/data
    environment:
      ES_HOSTS: '["https://es01:9200"]'
      BEATS_USER: beats_internal
      BEATS_PASSWORD: ${BEATS_PASSWORD}
      KIBANA_HOST: "https://kibana:5601"
      SSL_CERTIFICATE_AUTHORITIES: /usr/share/filebeat/certs/ca/ca.crt
    networks:
      - internal
    profiles:
      - beats
      - ingest
    depends_on:
      es01:
        condition: service_healthy
      setup-users:
        condition: service_completed_successfully
    labels:
      co.elastic.logs/module: filebeat

  heartbeat:
    image: docker.elastic.co/beats/heartbeat:${STACK_VERSION}
    volumes:
      - ./heartbeat/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro
      - ./heartbeat/monitors.d/:/usr/share/heartbeat/monitors.d/:ro
      - ./certs/entities/ca_pub/:/usr/share/heartbeat/certs/ca:ro
    environment:
      ES_HOSTS: '["https://es01:9200"]'
      BEATS_USER: beats_internal
      BEATS_PASSWORD: ${BEATS_PASSWORD}
      KIBANA_HOST: "https://kibana:5601"
      SSL_CERTIFICATE_AUTHORITIES: /usr/share/heartbeat/certs/ca/ca.crt
    networks:
      - internal
    profiles:
      - beats
      - ingest
    depends_on:
      es01:
        condition: service_healthy
      setup-users:
        condition: service_completed_successfully
    labels:
      co.elastic.logs/module: heartbeat

volumes:
  es01_data:
  kibana_data:
  logstash_data:
  filebeat_data:

networks:
  internal:
